### ISSUE TITLE
Fix sheet design

### ISSUE THREAD

**Issue by SameepAher** [Yatharth-Jain/Sem-2-Group-8#44]
Fix the positioning of some elements (cross button, edit button, add button, etc.) in the sheet.

![issue1](https://user-images.githubusercontent.com/96468766/177048195-7e6730e0-ca2b-4e8b-805a-3c22384accbb.png)

Reason for this issue might be clash of class names between sheet.css and style.css.

**Comment by Harjot4698** [comment]
hey can i solve this issue for you ?
